### ISSUE TITLE
V2 dataset contains only `.ply` files

### ISSUE THREAD

**Issue by KhanhNgoDuy** [CrisalixSA/h3ds#12]
Hi, thank you for the contributed dataset.

I downloaded the v2 dataset using [this link](https://drive.google.com/file/d/12zMORAGo6IArLS0wras2G_K-1yRak4pA/view?usp=sharing) from your github repo. But it contains only `.ply` files with no texture. I tried to use `kiuikit` to render a video from it, but the video only contains geometric information and no colors (the video is attached below).

Also, the dataset should come with RGB, mask images and camera pose I believe? Or do they come with the `H3DS_ACCESS_TOKEN`?

https://github.com/CrisalixSA/h3ds/assets/94754952/80aba55a-6eae-4af1-b04d-73356942ca5c

**Comment by pcaselles** [comment]
Hi @KhanhNgoDuy,

You can find the v2 version of the H3DS dataset [here](https://drive.google.com/file/d/1fkkThwVCsuWovh3Ksqzr25SP73-R5Y2D/view?usp=sharing). The link is now updated. After downloading you have to enter the H3DS_TOKEN to unzip the file. 

Indeed, the dataset contains cameras, posed RGB images (about 80-100 for each scene), binary masks, high resolution textured full head meshes and a registered 3DMMs.

Thank you,

Best,
Pol Caselles
