### ISSUE TITLE
Question about regions folder in each scene

### ISSUE THREAD

**Issue by yjhong89** [CrisalixSA/h3ds#7]
Dear author, 

Thanks for providing datasets.

While I am looking datasets, there is "regions" folder for each scene, containing 1) face.txt, 2) face_sphere.txt, 3) nose.txt.

What are they for ? 
And what is the meaning of sequence of integers in each regions text file ?

Thank you.
Best regards,
YJHong.

**Comment by eduardramon** [comment]
Hi @yjhong89 

These `regions.txt` are sets of vertices that define regions on the ground truth meshes of each scene. They can be used to compute metrics on different regions. Here is a description:
- `face.txt`: This region has been manually annotated and includes the frontal part of the face, including the ears, and part of the neck. We use this region to align the ground truth and predicted meshes, along with the landmarks as well.
- `face_sphere.txt`: This region has been computed automatically and it is defined as all the vertices that fall inside a sphere of radius 95mm centered at the tip of the nose. This region is typically found in the literature and is the one we report in H3D-Net for the face area.
- `nose.txt`: This region has been computed automatically and defines the part of the nose. We didn't use this region in the paper.

Best,
Eduard
