### ISSUE TITLE
Incorrect access password

### ISSUE THREAD

**Issue by wdings** [CrisalixSA/h3ds#8]

**Comment by baoachun** [comment]
The same problem

**Comment by pcaselles** [comment]
Hi @baoachun, 

To request access, please fill in the [contact form](https://docs.google.com/forms/d/e/1FAIpQLScpgNf0AA-2BuqcjDod-StNsolYm3DVLtLEdgROiX49xC83dQ/viewform) with your academic email. Your application will be reviewed and, after acceptance, you will receive a H3DS_ACCESS_TOKEN for each of the subsets. Each version of the dataset has a different access token.

Feel free to contact me if you have any other questions!
